apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "movie-chart.fullname" . }}-config
  labels:
    {{- include "movie-chart.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
