apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-api
  template:
    metadata:
      labels:
        app: movie-api
    spec:
{{- include "movie-chart.imageSet" . | nindent 6 }}
{{- include "movie-chart.pullingEnv" . | nindent 6 }}
{{- include "movie-chart.testingTemp" . | nindent 10}}

