apiVersion: v1
kind: Secret
metadata:
  name: {{ include "movie-chart.fullname" . }}-secret
  labels:
    {{- include "movie-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_URI: {{ ternary (printf "mongodb://%s:27017/movies" .Values.mongodb.fullnameOverride) .Values.externalMongoUri .Values.mongodb.enabled | quote }}
