events {}

http {
    upstream users_backend {
        server users-service:3000;
    }

    upstream products_backend {
        server products-service:3000;
    }

    server {
        listen 80;

        location /users/ {
            proxy_pass http://users_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location = /users {
            proxy_pass http://users_backend;
            proxy_set_header Host $host;
        }

        location /products/ {
            proxy_pass http://products_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location = /products {
            proxy_pass http://products_backend;
            proxy_set_header Host $host;
        }

        location = /health {
            default_type application/json;
            return 200 '{"status":"ok","service":"lb"}';
        }
    }
}
