apiVersion: v1
kind: Pod
metadata:
  name: curl2
  labels:
    app: curl2
    tier: backend
spec:
  containers:
  - name: curl
    image: lmacademy/alpine-curl:1.0.0
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
      requests:
        memory: "32Mi"
        cpu: "125m"