"""
=============================================================================
manage.py — Django's Command-Line Interface Entry Point
=============================================================================

This file is generated by `django-admin startproject` and should not need
editing. It sets the DJANGO_SETTINGS_MODULE environment variable and then
delegates to Django's management utility.

Common commands:
    python manage.py runserver       ← Start the dev server
    python manage.py migrate         ← Apply database migrations
    python manage.py makemigrations  ← Create migration files from model changes
    python manage.py createsuperuser ← Create an admin user
    python manage.py shell           ← Open a Python shell with Django loaded
    python manage.py test            ← Run tests

BEHIND THE SCENES:
Django's management commands are full Python classes discovered via
INSTALLED_APPS. When you run `python manage.py <command>`, Django:
1. Imports settings from DJANGO_SETTINGS_MODULE
2. Sets up logging, apps registry, and database connections
3. Discovers all management commands in installed apps
4. Finds and runs the matching command class
=============================================================================
"""

import os
import sys


def main():
    # Tell Django which settings module to use.
    # This must be set before any Django imports.
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? "
            "Did you forget to activate a virtual environment?"
        ) from exc

    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
