## @param customName allows to set a custoime resource name 
##        Defaults to {{ .Release.Name }}-{{ .Chart.Name }}
# customName: "my-custom-release"
customName: ""


## @param replicaCount Number of Nginx replicas to deploy 
replicaCount: 3

# environment: dev
# environment: production

## Settings for NGINX image
##
## @param image.name Nginx image name to use
## @param image.tag Nginx tag to use
image:
  name: nginx
  tag: 1.27.0


# Security context for the Nginx container
## @param securityContext.enable Enable or disable security context for the Nginx container
## @params securityContext.runAsUser The user ID to run the Nginx container as
## @params securityContext.fsGroup The group ID to run the Nginx container as
securityContext:
  enabled: true
  runAsUser: 0
  fsGroup: 2000


# NGINX Container ports
## 
## @param containerPorts.http
containerPorts:
  http: 80

## Settings for Nginx service
## Services is a map with the following structure:
##
## @param service[*].type The type of service in front oof the Nginx pods
## @param service[*].port The port where the service is receiving requests
services:
  svc1:
      type: ClusterIP
      port: 80
  svc2:
      type: NodePort
      port: 30007