services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: todo-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - todo-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: todo-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge
