apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: orders-app
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvb3JkZXJzZGI=
  JWT_SECRET: NTllMWRmNWFjM2VkOGVlNmY2ZGM2NDM5YzEzMDA3Nzg1OTYyOWQyOGM0OTk4YzFiNGI0OWIyZGExMGRhNmYwZQ==
