locals {
  commands = [
    for instance in var.instances : format(
      "ssh -i \"%s\" ubuntu@%s # %s private_ip=%s",
      var.private_key_path,
      instance.public_ip,
      instance.name,
      instance.private_ip
    )
  ]
}

resource "local_file" "ssh_commands" {
  filename        = var.output_path
  file_permission = "0644"
  content = join("\n", concat(
    [
      "# SSH commands for Loki student instances",
      "# Generated by Terraform",
      ""
    ],
    local.commands,
    [""]
  ))
}
