apiVersion: v1
kind: Pod
metadata:
  name: nginx-restricted
spec:
  containers:
  - name: nginx
    image: nginxinc/nginx-unprivileged:1.27.1
    ports:
    - containerPort: 80
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault